version: '3'

services:
  front-end:
    build: .
    image: front-end
    container_name: front-end
    networks:
      - infrastructure_default

networks:
  infrastructure_default:
    external: true